import type { Metadata } from "next";
import "./styles/base.sass";
import { Righteous } from "next/font/google";
import { BreakpointsContextProvider } from "./services/breakpoints";
import { Header } from "./sections/Header";

const righteous = Righteous({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--main-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={righteous.variable}>
        {/* <BreakpointsContextProvider> */}
        <Header />
        {children}
        {/* </BreakpointsContextProvider> */}
      </body>
    </html>
  );
}
